### ISSUE TITLE
Minor issues in staging 

### ISSUE THREAD

**Issue by sarinasindurakar** [younginnovations/iatipublisher#1251]
- [x]  Issue 1 
When user tries to publish the activity  from the activity detail page, the core element is complete message is shown even when core element is not completed.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/3cec9a26-47b0-4099-a11f-9277a8cf7a42)

- [x] Issue 2 (Salil)
The download  xls  popup is shown only after refreshing the page.

- [x] Issue 3
 When user edits the API token and verify the invalid token, the tag is  shown correct.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/23910f29-e017-423a-ae2b-162ab51d6375)

- [ ] Issue 4 
 IATI Validator message of sector and transaction is navigating the user to setting page.
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/a3363cb8-9d4d-40ee-bb82-80a4ef184138)

- [x] Issue 5
 When user  downloads the csv file for activity, the date is being downloaded in the humanitarian vocabulary  column.

- [x] Issue 6
  When user imports the activity including the sector , recipient region and country  in both transaction and activity level using the csv, xls and xml, both sector and recipient region and country in the activity and transaction  level is disabled  and data is shown in both the form.

- [x]  Issue 7 
Add validation in the result reference and indicator reference .If the reference  vocabulary and code in added in the result level then it cannot be included in the indicator level and vice versa.

- [x] Issue 8 (Salil)
 The support button is overlapping bulk publishing modal
![image](https://github.com/younginnovations/iatipublisher/assets/65848732/fc111518-db07-4fe3-bec6-783ff00c58bb)

- [x] Issue 9
When user adds the same language in the sector narrative no error message is shown.

![Image](https://github.com/younginnovations/iatipublisher/assets/65848732/059f9c54-f6a6-4e56-b87f-7fe34577c72f)

- [x]  Issue 10  
When user edits and tries to update the organization identifier and humanitarian scope , error message is shown but data is updated.
- [x]  Issue 11 (Salil)
When user cancels the import and again upload the file, the file upload popup  is shown only after refreshing the page.

**Comment by sarinasindurakar** [comment]
- [ ]  12 Add question mark in the last line.


![Image](https://github.com/younginnovations/iatipublisher/assets/65848732/ee81f1cc-31e0-4e2b-9dc1-e6ad4fd98aad)

**Comment by rajkarnikar11** [comment]
> 

issue 8 : Solved by moving the support button to the left when the bulk publish component is expanded
issue 11 :The state(in vuex) was not changed while canceling the import , fixed by updating state in vuex while the import model is cancled

**Comment by PG-Momik** [comment]
issue 1: Added explicit completeness check that was missing
issue 3: Changed logic to determine type of response from api when validating token
issue 9: Added missing validation that checked for 'unique_lang' validation in sector
issue 12: Added a '?' at the end of the text instead of '.' .

**Comment by sriza** [comment]
issue 5: Not an issue. Might be caused by some setting present in ms excel, works fine with libreoffice calc

**Comment by PG-Momik** [comment]
@DaveEade49  @emmajclegg @siwhitehouse @IsabelBirds 

These issues has been resolved and the fixes are now deployed to staging branch. Please have a look and let us know if issue persists. 
Thank you.

**Comment by DaveEade49** [comment]
@PG-Momik - Hi - Can you clarify more about issue 4? I've tried this one in Staging and Live and still get diverted to settings.

**Comment by DaveEade49** [comment]
@PG-Momik - issue 5 - which column in csv file is this issue in?

**Comment by DaveEade49** [comment]
**Summary of Testing**

- [ ] 1. Passed
- [ ] 2. This seems to work in staging and live ok.
- [ ] 3. Passed
- [ ] 4. Fail - still an issue
- [ ] 5. Fail - see other comments
- [ ] 6. Pass
- [ ] 7. Pass
- [ ] 8. Fail - still an issue, but the user can resolve by scrolling
- [ ] 9. Pass
- [ ] 10. Pass
- [ ] 11. Pass
- [ ] 12. Pass
- [ ] 13. Don't understand fix response in relation to original bug, also cannot recreate original - not sure where that screen in in which user story.

**Comment by praweshsth** [comment]
For no. 5, use single or double quote to make it string so that excel doesn't take it as date.

**Comment by PG-Momik** [comment]
@DaveEade49  issue 13 was seen in organisation : World Vegetable Center. This organisation had the following information in organisation-identifier:
1. Country: TW - Taiwan
2. Registration Agency : XM-DAC - OECD Development Assisatnce Committee
3. Registration number : 47008
4. Organisation-identifier: XM-DAC-47008

Before the fix, in the organisation-identifier edit page, an organisation could only chose organisation registration agency that had the country prefix (TW in this case) or the prefixes : XI or XR. Since the organisation had  Registration Agency with prefix XM, the data was considered invalid and would not be displayed. This was causing the form to flicker on initial load.

**Comment by DaveEade49** [comment]
@PG-Momik - Ah, ok thats great - I'll mark that one as closed.

**Comment by PG-Momik** [comment]
Hi @DaveEade49 ,

Regarding issue 5, we've made changes to how Humanitarian Scope Vocabulary in  csv are handled. Previously Humanitarian Scope Vocabulary cell would only consist one fo these code: 
1-2,
2-1,
99 

Now the downloaded csv will contain either one of the follwing :
1-2-Glide
2-1-Humanitarian Plan
99-Reporting Organisation

Similarly when importing csv, any/all of the following data will be considered valid csv data : 
1-2-Glide,
2-1-Humanitarian Plan,
99-Reporting Organisation
1-2,
2-1,
99
---
This change has been deployed to staging.

**Comment by DaveEade49** [comment]
Ok, happy with this fix - can we please apply to production.
