### ISSUE TITLE
Bug :408-routes-managed issue

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#444]
Context 
- Desktop
- Chrome 103.0.5060.114 

Preconditions
- stage.iatipublisher.yipl.com.np
- Username: Ram
- Password: 12345678

- [x] **Issue 1: Whenever the user clicks the edit button of iati-identifier, the edit form  disappears** 
Actual Result

https://user-images.githubusercontent.com/78422663/187429684-52bef8ae-5eb7-42b4-830a-007259eb137a.mp4

Excepted Result
- The edit form should be present

- [x] **Issue 2: When a user wants to click other-identifier, a back-end error message is displayed**
Actual Result

https://user-images.githubusercontent.com/78422663/187430673-dbf3d6b8-d0ba-4750-9d81-122c5f219c98.mp4

Excepted Result
- Edit Form should be displayed.

- [x] **Issue 3 : No validation in activity date** 
Actual Result
![Screenshot from 2022-08-30 17-44-31](https://user-images.githubusercontent.com/78422663/187431282-64e0a7a4-7531-42e4-ba58-bbb182eee4d9.png)
Excepted Result
- A proper validation should be done in the edit form. Please refer to IATI documentation( https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/activity-date/) 
- [x] **Issue 4 : collaboration-type element status isn't working.**
Actual Result
https://user-images.githubusercontent.com/78422663/187432600-377ff5cd-668a-421f-bdf7-291d5466dbbb.mp4
Excepted Result
- Should work properly 
- [x] **Issue 5: policy marker data is not displaying on the activity detail page**
Actual Result
https://user-images.githubusercontent.com/78422663/187433936-1347eae2-6ccc-469e-b9d6-d80595f2ea9d.mp4

Excepted Result
- Data should be displayed on the activity detail page
- [x] **Issue 6 :Invalid validation in planned disbursement** 
Actual Result
![Screenshot from 2022-08-30 18-04-11](https://user-images.githubusercontent.com/78422663/187434831-84644bcc-581d-4885-8d50-7b61486243b1.png)

Excepted Result
- a proper should be done 

- [x] **Issue 7 : transactions element status isn't working.**
Actual Result

https://user-images.githubusercontent.com/78422663/187436297-69b4fd84-7c76-4d50-84e3-7574b9dbadf7.mp4

Excepted Result
- Should work properly 
- [x]  **Issue 8: Invalid update message in legacy data**
Actual Result
https://user-images.githubusercontent.com/78422663/187437061-4557ea97-ddc9-4b69-9fbd-162f1a2d13d1.mp4

Excepted Result
- A valid update message should be displayed 

- [x] **Issue 9: Duplication of data in transaction detail page**
Actual Result
![Screenshot from 2022-08-30 18-17-51](https://user-images.githubusercontent.com/78422663/187437723-17c317fe-7b49-4189-8243-d2e9b2550171.png)

Excepted Result
- Duplication of data is not allowed 

- [x] **Issue 10: when the user saves a condition, the result automatically appears in the activity on the detail page**

Actual Result

https://user-images.githubusercontent.com/78422663/187440416-d55c9c5f-2c00-4fc1-b723-93add3c1e49d.mp4
Excepted Result 
- Only condition should appear on the activity detail  page

- [x]  **Issue 11 : Unwanted space in conditions** 

Actual Result
![Screenshot from 2022-08-30 18-35-10](https://user-images.githubusercontent.com/78422663/187441003-6deb14ff-ca22-40cb-a99b-a64be4e0457e.png)

Excepted Result
- Spacing should be reduced 

- [x] **Issue 14 : In transaction element Aid type(@code) value is not displayed on transaction detail page**
Actual Result
https://user-images.githubusercontent.com/78422663/187583774-ec6c9fc2-f955-432b-922d-d99642e8592e.mp4

Excepted Result
- the value should be displayed on the transaction detail page

- [x] **Issue 15: In transaction inconsistent UI for the same attribute** 
Actual Result
![Screenshot from 2022-08-31 09-02-18](https://user-images.githubusercontent.com/78422663/187585277-ae418e23-2c7c-431a-b67f-87b22430697a.png)

Expected Result
- UI should be inconsistent

- [x] **Issue 16: Inappropriate way to display a notification in  adding activity listing page**
Actual Result
https://user-images.githubusercontent.com/78422663/187592241-a54277d2-1e98-4733-9102-9c6f4c627a13.mp4

Expected Result
- There should be an appropriate way to display a notification

**Comment by sriza** [comment]
The issues I am looking after: 1, 2, 3, 6, 8 ,10

**Comment by man-git007** [comment]
The issue I am looking are: 4,5,7,9,13,14,15,16,17

**Comment by Sanilblank** [comment]
> The issues I am looking after: 1, 2, 3, 6, 8 ,10

Issue 2 has already been fixed

**Comment by jenishshrestha** [comment]
@SauravSilwal10 
Issue 13 - I think we don't need edit button in transactions.

The issue I am working on: 14, 15.

**Comment by Sanilblank** [comment]
The issues I am working on: 2, 12, 16

**Comment by jenishshrestha** [comment]
Completed Issue 14 and 15 and pushed into 408-routes-manage.

**Comment by man-git007** [comment]
> The issue I am looking are: 4,5,7,9,13,14,15,16,17

Issues 4,7,17 are fixed. Issue 5,9 have been assigned to @jenishshrestha Issue 16 has been assigned to @Sanilblank

**Comment by man-git007** [comment]
@SauravSilwal10 Regarding Issue 17, we will ignore the special characters for now.

**Comment by man-git007** [comment]
@SauravSilwal10 What does Issue 16 mean?

**Comment by SauravSilwal10** [comment]
@man-git007  whenever the user adds the activity, the activity created successfully popup appears at the top of add activity which interferes with the add activity button.

**Comment by man-git007** [comment]
> @man-git007 whenever the user adds the activity, the activity created successfully popup appears at the top of add activity which interferes with the add activity button.

OK. Let's ignore this for now but log this issue. We will work on it later

**Comment by jenishshrestha** [comment]
Issue 5 and 9 have been fixed and pushed.

**Comment by sriza** [comment]
Issue 1,3,4 and 8 are fixed and pushed.

**Comment by SauravSilwal10** [comment]
@man-git007  when the user clicks the updated button and time sort in descending order. The data after pagination are not displayed. Please review this issue.

https://user-images.githubusercontent.com/78422663/187643126-c9f14bb9-9244-4161-b688-b3ca4dbf70d5.mp4

**Comment by jenishshrestha** [comment]
Issue no. 10 and 11 has been fixed and pushed.

**Comment by SauravSilwal10** [comment]
@man-git007 Regarding issue 7. When a user wants to save the transactions edit the form, a back-end error message is displayed. Please have a look

https://user-images.githubusercontent.com/78422663/187661969-792c23b2-bb83-4182-97a0-e386f3fbcb67.mp4

**Comment by SauravSilwal10** [comment]
@Sanilblank Activity listing page publish button is not working .Please have a look.

https://user-images.githubusercontent.com/78422663/187666743-f319e9e2-8802-4a2b-b296-ec0c2fac6a59.mp4

**Comment by SauravSilwal10** [comment]
@Sanilblank  Regrading Issue 2 .Value of other-identifier is not displayed on activity detail page .Please review again. 

https://user-images.githubusercontent.com/78422663/187667921-2204b92c-451f-4e19-acda-854ffb6319db.mp4

**Comment by SauravSilwal10** [comment]
@jenishshrestha 

- [ ] **Issue 1: UI breakdown**
![Screenshot from 2022-08-31 17-13-31](https://user-images.githubusercontent.com/78422663/187668650-4d921ee3-7ab8-4f60-93b0-b506d315a1c6.png)

- [ ] **Issue 2 : Spacing is needed** 
![Screenshot from 2022-08-31 17-14-26](https://user-images.githubusercontent.com/78422663/187668804-b0485912-ebd9-4074-bdfa-a9b50277e8cb.png)
Also please review this issue #420 issue 3

**Comment by Sanilblank** [comment]
Issues 2, 12 and 16 have been fixed and pushed.
Regarding other identifier info not being shown in detail page, form rendering and storing in db as well as retrieval from db are working as intended.
It seems to be an issue in the FE side @jenishshrestha please look into it.

**Comment by Sanilblank** [comment]
> @Sanilblank Activity listing page publish button is not working .Please have a look.
> 
>  5.1.mp4

This issue has been fixed and pushed

**Comment by Sanilblank** [comment]
> Collaborator

I have worked on this issue as well.

**Comment by SauravSilwal10** [comment]
@man-git007 when user saves the recipient region and period edit form. A backend error message is displayed. Please have a look.

https://user-images.githubusercontent.com/78422663/187852667-1235058f-77e8-4f30-933e-2bf3208707d0.mp4

**Comment by SauravSilwal10** [comment]
> Issues 2, 12 and 16 have been fixed and pushed. Regarding other identifier info not being shown in detail page, form rendering and storing in db as well as retrieval from db are working as intended. It seems to be an issue in the FE side @jenishshrestha please look into it.

@Sanilblank issue 12 still exists. Can you review it again?

https://user-images.githubusercontent.com/78422663/187855001-05d1a945-fb3c-41ac-8868-7ebc893791e4.mp4

**Comment by Sanilblank** [comment]
> > Issues 2, 12 and 16 have been fixed and pushed. Regarding other identifier info not being shown in detail page, form rendering and storing in db as well as retrieval from db are working as intended. It seems to be an issue in the FE side @jenishshrestha please look into it.
> 
> @Sanilblank issue 12 still exists. Can you review it again?
> 
>  12.mp4

This is because the new branch with the problem fixes has not yet been deployed to staging. @SauravSilwal10
